name: Feed Cron

on:
  schedule:
    - cron: "0 * * * *" # UTC
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      # 調べ方 https://booknotion.site/setting-databaseid
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDER_DATABASE_ID: ${{ secrets.NOTION_FEEDER_DATABASE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - name: Update Notion Feed
        # npm run buildはlocalでしてdistに入れてcommitもしちゃう
        run: npm run feed
