name: Feed Cron

on:
  schedule:
    - cron: "0 * * * *" # UTC
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      # 調べ方 https://booknotion.site/setting-databaseid
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDER_DATABASE_ID: ${{ secrets.NOTION_FEEDER_DATABASE_ID }}
      DENO_DIR: deno_cache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
         deno-version: v2.x
      - name: Restore Deno cache
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }} 
          key: ${{ hashFiles('deno.lock') }}
      - name: Update Notion Feed
        run: deno run --allow-net --allow-read --allow-env src/index.ts